export const simEmojis: Record<string, string> = {
    // Estágios de Vida
    'Recém-nascido': '👶',
    'Bebê': '👶',
    'Criança de colo': '🧒',
    'Criança': '🧒',
    'Adolescente': '🧑',
    'Jovem Adulto': '🧑',
    'Adulto': '🧑',
    'Idoso': '👴',

    // Ocultos
    'Humano': '👤',
    'Vampiro': '🧛',
    'Feiticeiro(a)': '🧙',
    'Lobisomem': '🐺',
    'Lobisim': '🐺',
    'Sereia/o': '🧜',
    'Alienígena': '👽',
    'Sim Planta': '🌿',
    'Fantasma': '👻',

    // Animais / Pets
    'Cão': '🐶',
    'Gato': '🐱',
    'Cavalo': '🐴',
    'Galinha': '🐔',
    'Galo': '🐓',
    'Pintinho': '🐤',
    'Galinha Dourada': '✨',
    'Galinha do Vazio': '🌌',
    'Hamster': '🐹',
    'Rato': '🐭',
    'Porquinho-da-índia': '🐹',
    'Ouriço': '🦔',
    'Filhote': '🐾',
    'Potro': '🐴',

    // Aspirações
    // Fortuna
    'Barão das Mansões': '💰',
    'Fabulosamente Rico': '💰',
    // Amor
    'Alma Gêmea': '❤️',
    'Serial Romântico': '❤️',
    // Família
    'Super Pai/Mãe': '👪',
    'Grande Família Feliz': '👪',
    'Vampiro Familiar': '🦇',
    // Criatividade
    'Autor Best-Seller': '📖',
    'Pintor Extraordinário': '🎨',
    'Mestre da Música': '🎵',
    'Comediante Brilhante': '😂',
    // Conhecimento
    'Nerd do Computador': '💻',
    'Gênio da Lógica': '♟️',
    'Especialista em Poções': '🧪',
    'Mestre Vampiro': '🧛',
    'Curador de Museu': '🏛️',
    'Acadêmico': '🎓',
    // Esporte
    'Fisiculturista': '💪',
    'Atleta Extraordinário': '🏆',
    // Natureza
    'Entusiasta da Pesca': '🎣',
    'Botânico': '🌿',
    'Curador da Selva': '🧭',
    'Guardião do Monte Komorebi': '⛰️',
    // Popularidade
    'Amigo do Mundo': '🌍',
    'Líder da Trupe': '👑',
    'Piada Viva': '🤡',
    'Ícone da Festa': '🎉',
    // Animais
    'Amigo dos Animais': '🐾',
    'Treinador(a) Campeão(ã)': '🐕',
    'Fazendeiro(a)': '🚜',
    // Localização e Estilo de Vida
    'Nativo(a) da Cidade': '🏙️',
    'Mestre da Cultura de Selvadorada': '🗿',
    'Vida Sustentável': '♻️',
    'Fabricante Mestre': '🛠️',
    'Senhor(a) do Néctar': '🍷',
    'Explorador(a) do Espaço': '🚀',
    'Paranormal': '👻',
    'Lobisomem Alfa': '🐺',
    'Mágico(a) Supremo(a)': '✨',
    'Filho(a) das Ilhas': '🏝️',
    // Criança
    'Gênio Infantil': '🧠',
    'Prodígio Artístico': '🎨',
    'Turbilhão Social': '🗣️',
    'Campeão de Criatividade': '⭐',

    // Qualidades / Traços
    // Emocionais
    'Alegre': '😄',
    'Bom Humor': '😊',
    'Mal-Humorado': '😠',
    'Dramático': '🎭',
    'Infeliz': '😢',
    'Carinhoso': '💖',
    'Brincalhão': '🤪',
    'Amigável': '🤝',
    // Mentais
    'Genial': '🧠',
    'Analítico': '📊',
    'Criativo': '🎨',
    'Curioso': '🧐',
    'Concentrado': '🎯',
    'Nerd': '🤓',
    'Geek': '🕹️',
    'Lógico': '🧩',
    'Desonesto': '🤥',
    // Sociais
    'Extrovertido': '🗣️',
    'Tímido': '😳',
    'Solitário': '🚶',
    'Sedutor': '😏',
    'Amável': '🥰',
    'Grosso': '😤',
    'Manipulador': '🐍',
    'Festeiro': '🥳',
    'Engraçado': '😂',
    // Físicos
    'Atlético': '💪',
    'Preguiçoso': '🥱',
    'Descuidado': '🗑️',
    'Guloso': '🍔',
    'Limpo': '✨',
    'Noturno': '🦉',
    'Madrugador': '🌅',
    // Românticos
    'Romântico': '🌹',
    'Fiel': '💍',
    'Ciumento': '👀',
    'Pervertido': '😈',
    // Negativos
    'Malvado': '👿',
    'Mesquinho': ' Scrooge',
    'Antipático': '😒',
    'Egoísta': '👑',
    'Invejoso': '🍏',
    'Irritadiço': '💢',
    // Especiais
    'Aventureiro': '🧗',
    'Perfeccionista': '📐',
    'Desastrado': '🤕',
    'Ambicioso': '📈',
    'Neurótico': '😰',
    'Workaholic': '💼',
    'Materialista': '💎',
    'Amante de Animais': '🐾',
    'Amante da Natureza': '🌲',
    'Eco-Consciente': '♻️',
    'Autoconfiante': '😎',
    'Apreciador de Livros': '📚',
    'Detesta Crianças': '👶🚫',
    'Infantil': '🧸',
    'Amante de Cachorros': '🐶',
    'Amante de Gatos': '🐱',
    'Não-comprometido': '🤷',
    'Cleptomaníaco': '🥷',
    'Paranóico': '👀',

    // Habilidades
    // Criativas
    'Pintura': '🎨',
    'Escrita': '✍️',
    'Fotografia': '📸',
    'Escultura': '🗿',
    'Fabricação de Velas': '🕯️',
    'Costura': '🧵',
    'Arranjo Floral': '💐',
    'Mixologia': '🍹',
    // Musicais
    'Violão': '🎸',
    'Piano': '🎹',
    'Violino': '🎻',
    'Bateria': '🥁',
    'Baixo': '🎸',
    'DJ': '🎧',
    'Canto': '🎤',
    // Conhecimento / Técnicas
    'Lógica': '🧠',
    'Programação': '💻',
    'Robótica': '🤖',
    'Eletrônica': '🔌',
    'Foguete': '🚀',
    'Pesquisa e Debate': '⚖️',
    // Sociais
    'Carisma': '🗣️',
    'Comédia': '😂',
    'Travessura': '🃏',
    'Transmissão ao Vivo': '📹',
    // Natureza
    'Jardinagem': '🌱',
    'Pesca': '🎣',
    'Rastreamento': '🐾',
    'Astrologia': '🔭',
    'Veterinária': '⚕️',
    'Escalada': '🧗',
    'Esqui': '⛷️',
    'Snowboard': '🏂',
    'Mergulho Livre': '🤿',
    // Físico
    'Fitness': '💪',
    'Natação': '🏊',
    // Culinária
    'Culinária': '🍳',
    'Gastronomia': '🍽️',
    'Fabricação de Néctar': '🍷',
    // Dom do Lar
    'Criatividade (Infantil)': '🖍️',
    'Videogame': '🎮',
    'Trabalho Mental (Criança)': '🧩',
    'Motor (Criança)': '🏃',
    'Socialização (Criança)': '🧒',

    // Carreiras
    'Astronauta': '🚀',
    'Atleta': '⚽',
    'Médico(a)': '⚕️',
    'Cientista': '🔬',
    'Detetive': '🔍',
    'Engenheiro(a)': '⚙️',
    'Advogado(a)': '⚖️',
    'Político(a)': '🏛️',
    'Ator/Atriz': '🎭',
    'Músico(a)': '🎵',
    'Escritor(a)': '✍️',
    'Artista / Pintor(a)': '🖌️',
    'Comediante': '🎤',
    'Empresário(a)': '💼',
    'Hacker / Programador(a)': '💻',
    'Executivo(a)': '🏢',
    'Financista': '📈',
    'Influencer': '📱',
    'Streamer': '📹',
    'Chef': '🍳',
    'Crítico(a) de Gastronomia': '🍽️',
    'Veterinário(a)': '🐾',
    'Botânico(a)': '🌿',
    'Policial': '👮',
    'Agente Secreto': '🕵️',
    'Militar': '🎖️',
    'Bombeiro(a)': '🚒',
    'Professor(a)': '🍎',
    'Conselheiro(a)': '🤝',
    'Criador(a) de Conteúdo': '🕹️',
    'Chefe do Crime': '😈',
    'Vilão(a) em Ascensão': '🦹',
    'Alquimista': '🧪',
    'Investigador(a) Paranormal': '🔦',
    'Gamer Profissional': '🎮',
    'Desempregado(a)': '🛋️',
    'Aposentado(a)': '👴',
    'Outra': '💼',
};

export function getSimEmoji(value: string | undefined | null, fallback = ''): string {
    if (!value) return fallback;
    return simEmojis[value] || fallback;
}

export function withEmoji(value: string | undefined | null, defaultEmoji = ''): string {
    if (!value) return '';
    const emoji = getSimEmoji(value, defaultEmoji);
    return emoji ? `${emoji} ${value}` : value;
}
